### ISSUE TITLE
Enable P12?

### ISSUE THREAD

**Issue by 4-3is4-me** [yokobond/scratch-microbit-more#2]
Hello, is it possible to enable the use of P12? There are some accessories that make use of P12, some motor driver boards for example. The extension is wonderful.
Thank you.

**Comment by yokobond** [comment]
I didn't notice P12 is using by applications. It should be controllable by microbit more. 
It can do with adding the pin index to GPIO on both of micro:bit firmware and Scratch extension code. 
I'm working on big refactoring for micro:bit v2. This will be added to the next version.

**Comment by yokobond** [comment]
This project moved to a new repository [yokobond/mbit-more-v2](https://github.com/yokobond/mbit-more-v2).
P12 can be controlled in the new version.
