### ISSUE TITLE
Not able to flash Mcirobit V.5.0 .hex or any previous version

### ISSUE THREAD

**Issue by Nitesh-AI** [yokobond/scratch-microbit-more#3]
Sir,
The microbit more hex file provided here :https://lab.yengawa.com/project/scratch-microbit-more/#i-8 are not working. I tried All most all of versions.
Issue: My microbit got disconnected when i burn hex in microbit with below fail log.
error: The application image is not compatible with the target.
type: user

**Comment by yokobond** [comment]
Possibly your target is micro:bit v2?
Guidance on using the latest micro:bit revision https://tech.microbit.org/latest-revision/

Currently microbit-more does not work with v2. (ref. yokobond/scratch-microbit-more#4)

**Comment by yokobond** [comment]
This project moved to a new repository [yokobond/mbit-more-v2](https://github.com/yokobond/mbit-more-v2).
That new version works on micro:bit v2 and also v1(restricted).
