### ISSUE TITLE
Magnetic force block returns UNDEFINED instead of actual value

### ISSUE THREAD

**Issue by mrhopeedu** [yokobond/scratch-microbit-more#5]
Hi Team,
It appeared the magnetic force block does not return any value.
I tested it by putting it near a metal or magnet, it says undefined instead of actual magnetic value. 
See screenshot:
[](https://i.imgur.com/TX50moJ.png)

To make sure it's nothing to do with the microbit, I tested with makecode and it works fine there. 
I noted there's no block in Microbit More than dows the calibration so wondering if that's the problem as in makecode, we have a block that calibrate the microbit. 

Thanks for taking time looking into this.

**Comment by yokobond** [comment]
This project moved to a new repository [microbit\-more/mbit\-more\-v2](https://github.com/microbit-more/mbit-more-v2).

**Comment by mrhopeedu** [comment]
Thank you sir @yokobond , should I log the issue in the new repository?
